services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000" # cổng server
    env_file:
      - ./.env       # file .env ở thư mục gốc chứa MONGOSV, etc
    volumes:
      - ./server:/app     # mount code để thay đổi tự cập nhật
      - /app/node_modules # tránh ghi đè node_modules
    command: npm start           # hoặc node index.js nếu bạn muốn
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    ports:
      - "3000:3000" # cổng client
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true  # Giúp vite/watch file tốt hơn trong Docker
    depends_on:
      - server

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017" # cổng MongoDB
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data:
